#!/usr/bin/env bash
set -euo pipefail

cd /home/jeremy/orange-gop-split-a16

if [[ -z "${XAUTHORITY:-}" ]]; then
  export XAUTHORITY="$HOME/.Xauthority"
fi

sudo env DISPLAY="${DISPLAY:-}" XAUTHORITY="${XAUTHORITY:-}" \
  ORANGE_GUI_RECORDING_SINK_MODE="${ORANGE_GUI_RECORDING_SINK_MODE:-}" \
  ORANGE_RECORDING_DETECT_PRIORITY=1 \
  ORANGE_YOLO_DETACH_INPUT=1 \
  ORANGE_YOLO_READY_EVENT_FASTPATH=1 \
  ORANGE_YOLO_PERF_LOG=1 \
  ORANGE_YOLO_PERF_SAMPLE=1 \
  ORANGE_CROP_COPY_TIMING=0 \
  ORANGE_CROP_STAGE_SOURCE=1 \
  ORANGE_CROP_PREVIEW_DISABLE="${ORANGE_CROP_PREVIEW_DISABLE:-0}" \
  ORANGE_DISPLAY_PREVIEW_MAX_FPS="${ORANGE_DISPLAY_PREVIEW_MAX_FPS:-}" \
  ORANGE_ANALYTICS_EARLY_OWNED_FRAME=1 \
  ORANGE_NVENC_EXTRA_OUTPUT_DELAY="${ORANGE_NVENC_EXTRA_OUTPUT_DELAY:-}" \
  ORANGE_NVENC_EXTRA_OUTPUT_DELAY_CAM_2010095="${ORANGE_NVENC_EXTRA_OUTPUT_DELAY_CAM_2010095:-}" \
  ORANGE_NVENC_EXTRA_OUTPUT_DELAY_CAM_2010096="${ORANGE_NVENC_EXTRA_OUTPUT_DELAY_CAM_2010096:-}" \
  ORANGE_NVENC_SPLIT_HARVEST="${ORANGE_NVENC_SPLIT_HARVEST:-0}" \
  ORANGE_NVENC_HARVEST_DELAY_US="${ORANGE_NVENC_HARVEST_DELAY_US:-0}" \
  ORANGE_NVENC_HARVEST_DELAY_US_CAM_2010095="${ORANGE_NVENC_HARVEST_DELAY_US_CAM_2010095:-}" \
  ORANGE_NVENC_HARVEST_DELAY_US_CAM_2010096="${ORANGE_NVENC_HARVEST_DELAY_US_CAM_2010096:-}" \
  ORANGE_YOLO_AFFINITY_CAM_2010095=2 \
  ORANGE_YOLO_AFFINITY_CAM_2010096=4 \
  ORANGE_YOLO_RT_PRIORITY="${ORANGE_YOLO_RT_PRIORITY:-0}" \
  ORANGE_YOLO_RT_POLICY="${ORANGE_YOLO_RT_POLICY:-fifo}" \
  ./targets/release/orange
