#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  run_spatial_roi_diagnostic_2010093.sh [--spec <path>] [--orange-client <path>] [--execute]

Validates and prints the versioned one-camera/four-fixed-ROI diagnostic smoke
for camera 2010093 (4512x4512 at 100 FPS, source GPU 3). The four quadrants
are plumbing/encoder validation geometry only; they are not accepted physical
compartment geometry.

Default: validate/print only. No camera, CUDA, NVENC, or media work occurs.
--execute: run orange_client against the camera and write full-frame plus
           spatial-ROI recording artifacts under
           /home/jeremy/orange_data/exp/unsorted. Hardware/media execution
           requires this explicit flag.
The combined product uses a supervised external_ipc full-frame split-GOP
contract on GPUs 3 and 4. Each of the four P1/VBR-Q20/GOP-25 ROI streams remains
an independently finalized single-shard product generated by the ROI recorder;
the explicit camera-perspective placement is GPU 1,2,1,2.
After a successful --execute, run the read-only acceptance verifier against
the exact recording folder printed by orange_client (do not select an old
folder by globbing):
  python3 tools/validate_spatial_roi_recording.py --require-ffprobe \
    /home/jeremy/orange_data/exp/unsorted/2010093_spatial_roi_diagnostic_plumbing_100fps_gpu3_v1/<run-id>

Options:
  --spec <path>              Experiment spec (default: the versioned repo spec).
  --orange-client <path>     orange_client binary (default: targets/release/orange_client).
  --execute                  Opt in to hardware/media execution.
  --help
EOF
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SPEC="$REPO_ROOT/experiment_specs/2010093_spatial_roi_diagnostic_plumbing_100fps_gpu3_v1.json"
ORANGE_CLIENT="$REPO_ROOT/targets/release/orange_client"
EXECUTE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --spec)
      shift
      [[ $# -gt 0 ]] || { echo "--spec requires a value." >&2; exit 2; }
      SPEC="$1"
      shift
      ;;
    --orange-client)
      shift
      [[ $# -gt 0 ]] || { echo "--orange-client requires a value." >&2; exit 2; }
      ORANGE_CLIENT="$1"
      shift
      ;;
    --execute)
      EXECUTE=1
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unsupported argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ "$SPEC" != /* ]]; then
  SPEC="$REPO_ROOT/$SPEC"
fi
if [[ "$ORANGE_CLIENT" != /* ]]; then
  ORANGE_CLIENT="$REPO_ROOT/$ORANGE_CLIENT"
fi
SPEC="$(realpath -e "$SPEC")"
ORANGE_CLIENT="$(realpath -e "$ORANGE_CLIENT")"

python3 - "$SPEC" "$REPO_ROOT" <<'PY'
import hashlib
import json
import sys
from pathlib import Path

spec_path = Path(sys.argv[1])
repo_root = Path(sys.argv[2]).resolve()
spec = json.loads(spec_path.read_text(encoding="utf-8"))


def require(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(f"[spatial-roi-diagnostic] invalid spec: {message}")


experiment_id = "2010093_spatial_roi_diagnostic_plumbing_100fps_gpu3_v1"
require(spec.get("experiment_id") == experiment_id, "unexpected experiment_id")
require(spec.get("selection") == {"camera_serials": ["2010093"], "gpu_ids": [3]},
        "selection must contain only camera 2010093 on source GPU 3")

fixed = spec.get("fixed", {})
require(fixed.get("duration_s") == 3 and fixed.get("warmup_s") == 1,
        "diagnostic duration/warmup must remain 3s/1s")
require(fixed.get("output_root") == "/home/jeremy/orange_data/exp/unsorted",
        "execute output_root must be the durable local acquisition root")
require(fixed.get("stream_only") is False,
        "full-frame recording must remain enabled (stream_only=false)")
require(fixed.get("recording_sink_mode") == "external_ipc",
        "the combined full-frame plus ROI product requires external_ipc")
require(fixed.get("display") is False and fixed.get("yolo") is False,
        "display and YOLO must be disabled")
require(fixed.get("yolo_worker") is False and fixed.get("pose_worker") is False,
        "YOLO and pose workers must be disabled")
require(fixed.get("sync_mode") == "free_run",
        "diagnostic sync mode must remain free_run")
require(fixed.get("config_folder") ==
        "config/validated_split_gop_hevc_100fps_gop25_fourcam_a16",
        "config_folder must remain the versioned four-camera profile")

external_contract = fixed.get("external_recorder_contract", {})
require(external_contract.get("schema_id") == "orange.external_recorder.contract" and
        external_contract.get("schema_version") == 1 and
        external_contract.get("mode") == "diagnostic_ipc_v1" and
        external_contract.get("supervise_processes") is True,
        "combined recording requires the supervised external recorder contract v1")
require(external_contract.get("recorder_tool_path") ==
        "targets/release/external_recorder_ipc_probe",
        "external recorder tool must be the repo-relative release binary")
recorder_tool = repo_root / external_contract["recorder_tool_path"]
require(recorder_tool.is_file() and not recorder_tool.is_symlink(),
        "external recorder release binary is missing or symlinked")
require(recorder_tool.stat().st_mode & 0o111,
        "external recorder release binary is not executable")
require(external_contract.get("artifact_root") ==
        "/tmp/orange_external_recorder_spatial_roi_2010093" and
        external_contract.get("session_id") == experiment_id,
        "external recorder identity/root must be unique to the 2010093 diagnostic")
for required_flag in (
    "require_summary", "require_status", "require_video_sanity",
    "require_merged_mp4", "require_gop_routing", "require_storage_preflight",
    "require_protocol_hello", "require_frame_identity_proof",
):
    require(external_contract.get(required_flag) is True,
            f"external recorder {required_flag} must remain enabled")
require(external_contract.get("preserve_shard_mp4s") is False,
        "diagnostic must not preserve intermediate shard MP4s")
require(list(external_contract.get("streams", {})) == ["2010093"],
        "external recorder contract must contain only camera 2010093")
external_stream = external_contract["streams"]["2010093"]
require(external_stream.get("stream_id") == "2010093" and
        external_stream.get("camera_serial") == "2010093" and
        external_stream.get("analytics_gpu_id") == 3 and
        external_stream.get("recorder_gpu_id") == 3 and
        external_stream.get("routing_policy") == "gop_modulo" and
        external_stream.get("expected_shard_gpu_ids") == [3, 4],
        "full-frame recording must use the validated 2010093 split-GOP pair [3,4]")
external_root = "/tmp/orange_external_recorder_spatial_roi_2010093"
expected_external_paths = {
    "summary_json": f"{external_root}/Cam2010093_external_summary.json",
    "status_json": f"{external_root}/Cam2010093_external_status.json",
    "video_sanity_json": f"{external_root}/Cam2010093_external_video_sanity.json",
    "mp4": f"{external_root}/Cam2010093_external.mp4",
    "metadata_csv": f"{external_root}/Cam2010093_external_meta.csv",
    "gop_routing_csv": f"{external_root}/Cam2010093_external_gop_routing.csv",
}
for field, expected_path in expected_external_paths.items():
    require(external_stream.get(field) == expected_path,
            f"external recorder {field} is not the canonical 2010093 path")
require({key: external_stream.get(key) for key in (
            "encode_fps", "encode_max_fps", "encode_queue_depth", "prewarm_slots",
            "prewarm_bytes", "prewarm_peer_copy", "codec", "preset", "tuning",
            "gop", "bitrate_bps", "max_bitrate_bps", "vbv_buffer_size",
        )} == {
            "encode_fps": 100,
            "encode_max_fps": 0,
            "encode_queue_depth": 32,
            "prewarm_slots": 4,
            "prewarm_bytes": 20358144,
            "prewarm_peer_copy": True,
            "codec": "hevc",
            "preset": "p1",
            "tuning": "ll",
            "gop": 25,
            "bitrate_bps": 150000000,
            "max_bitrate_bps": 150000000,
            "vbv_buffer_size": 150000000,
        }, "external recorder encoding contract drifted")

config_folder = repo_root / fixed["config_folder"]
camera_config_path = config_folder / "2010093.json"
require(camera_config_path.is_file() and not camera_config_path.is_symlink(),
        f"camera config is missing or symlinked: {camera_config_path}")
camera_config = json.loads(camera_config_path.read_text(encoding="utf-8"))
require(camera_config.get("schema_id") == "orange.camera.config" and
        camera_config.get("schema_version") == 3 and
        camera_config.get("device_serial_number") == "2010093",
        "camera config identity must be 2010093 schema v3")
require(camera_config.get("width") == 4512 and camera_config.get("height") == 4512,
        "camera config must be 4512x4512")
require(camera_config.get("frame_rate") == 100 and
        camera_config.get("pixel_format") == "Mono8" and
        camera_config.get("source_gpu_id") == 3 and
        camera_config.get("gpu_direct") is True,
        "camera config must be 100 FPS Mono8 GPUDirect on source GPU 3")
recording = camera_config.get("recording", {})
require(recording.get("profile_name") ==
        "validated_split_gop_hevc_100fps_gop25_fourcam_a16" and
        recording.get("mode") == "split_gop" and
        recording.get("split_gop", {}).get("encoder_gpu_ids") == [3, 4] and
        recording.get("split_gop", {}).get("strict") is True,
        "camera config must retain the validated strict split-GOP [3,4] profile")

roi_config = fixed.get("spatial_roi_recording", {})
require(roi_config.get("schema_id") == "orange.spatial_roi_recording.config" and
        roi_config.get("schema_version") == 3 and
        roi_config.get("enabled") is True and
        roi_config.get("backend") == "independent_hevc_external_ipc" and
        roi_config.get("strict") is True and
        roi_config.get("source_cadence") == "every_recording_frame",
        "spatial ROI config must remain strict independent-HEVC schema v3")
require(roi_config.get("pixel_contract") == {
            "source_format": "mono8",
            "no_resize": True,
            "no_color_conversion": True,
            "output_alignment_px": 2,
            "padding_value_mono8": 0,
        }, "spatial ROI pixel contract drifted")
require(roi_config.get("encode_profile") == {
            "name": "hevc_p1_low_latency_vbr_q20_gop25_v1",
            "codec": "hevc",
            "preset": "p1",
            "tuning": "ll",
            "lossless": False,
            "rate_control_mode": "vbr",
            "quality_value": 20,
            "gop_length": 25,
            "aq": False,
            "temporal_aq": False,
            "lookahead": False,
            "lookahead_depth": 0,
        }, "spatial ROI P1 encode profile drifted")
require(roi_config.get("buffering") == {
            "pool_frames_per_stream": 32,
            "queue_frames_per_stream": 64,
        }, "spatial ROI buffering contract drifted")
require(roi_config.get("recording_limits") == {
            "max_frames_per_stream": 2000,
            "max_media_bytes_per_stream": 17179869184,
            "max_evidence_bytes_per_stream": 268435456,
        }, "spatial ROI recording limits drifted")
require(roi_config.get("admission") == {
            "max_rois_per_camera": 4,
            "max_total_rois": 4,
            "max_total_pixel_rate": 3000000000,
            "max_total_encoder_streams": 4,
            "max_total_pool_bytes": 1000000000,
            "max_total_queue_frames": 512,
            "max_total_media_bytes": 68719476736,
            "max_total_evidence_bytes": 1073741824,
        }, "spatial ROI admission contract drifted")
require(list(roi_config.get("cameras", {})) == ["2010093"],
        "spatial ROI config must contain only camera 2010093")
camera = roi_config["cameras"]["2010093"]
require(camera.get("camera_id") == 0 and camera.get("camera_serial") == "2010093",
        "camera 2010093 must use runtime/Shaman camera_id 0")
require(camera.get("native_raster") == {"width": 4512, "height": 4512} and
        camera.get("source_frame_rate") == 100 and
        camera.get("arena_group_id") == "diagnostic_quadrants" and
        camera.get("allow_roi_overlap") is False,
        "spatial ROI camera geometry/cadence contract drifted")

expected_authorities = {
    "layout": {
        "id": "2010093_diagnostic_layout_v1",
        "path": "experiment_specs/spatial_roi_diagnostic_authority/2010093_diagnostic_layout_v1.json",
        "size_bytes": 1113,
        "sha256": "sha256:3c426ab2d4be238dca72b2d96f8dbbcc0de585acdcb5ebef4b1f182f71339656",
        "schema_id": "orange.spatial_roi_diagnostic_authority.layout",
    },
    "materialization": {
        "id": "2010093_diagnostic_materialization_v1",
        "path": "experiment_specs/spatial_roi_diagnostic_authority/2010093_diagnostic_materialization_v1.json",
        "size_bytes": 1651,
        "sha256": "sha256:5fa379643059c60edc111ea0b89b00cb7ac10dff4f04cee8c17a2763e2ce1b83",
        "schema_id": "orange.spatial_roi_diagnostic_authority.materialization",
    },
    "registration": {
        "id": "2010093_diagnostic_registration_v1",
        "path": "experiment_specs/spatial_roi_diagnostic_authority/2010093_diagnostic_registration_v1.json",
        "size_bytes": 811,
        "sha256": "sha256:cef85a0d4f51a4ef6b0a64fbf5e849f5947475bf11aa586a10f8553b6228e227",
        "schema_id": "orange.spatial_roi_diagnostic_authority.registration",
    },
}
authority_index = spec.get("diagnostic_authority", {})
require(authority_index.get("schema_id") ==
        "orange.spatial_roi_diagnostic_authority.index" and
        authority_index.get("schema_version") == 1 and
        authority_index.get("closed") is True and
        authority_index.get("status") == "diagnostic_not_physical_acceptance",
        "diagnostic authority index must remain closed version 1 diagnostic metadata")
require(authority_index.get("camera_serial") == "2010093" and
        authority_index.get("runtime_camera_id") == 0 and
        authority_index.get("runtime_mapping") ==
        "normal_four_camera_rig_inventory_2010093_to_2010096_maps_0_to_3" and
        authority_index.get("coordinate_space") == "camera_native_0_indexed" and
        authority_index.get("native_raster") == {"width": 4512, "height": 4512},
        "diagnostic authority index camera-native identity mismatch")
require(set(authority_index.get("artifacts", {})) == set(expected_authorities),
        "diagnostic authority index must contain exactly three authority roles")
for role, expected in expected_authorities.items():
    descriptor = authority_index["artifacts"].get(role, {})
    expected_descriptor = {key: expected[key] for key in ("id", "path", "size_bytes", "sha256")}
    require(descriptor == expected_descriptor,
            f"{role} authority descriptor is not the hardcoded accepted artifact")
    require(camera.get(role) == {"id": expected["id"], "sha256": expected["sha256"]},
            f"{role} spatial ROI authority reference mismatch")
    relative_path = Path(expected["path"])
    authority_path = repo_root / relative_path
    require(authority_path.is_file() and not authority_path.is_symlink(),
            f"{role} authority artifact is missing or symlinked")
    resolved_authority_path = authority_path.resolve()
    try:
        resolved_authority_path.relative_to(repo_root)
    except ValueError:
        raise SystemExit(
            f"[spatial-roi-diagnostic] invalid spec: {role} authority path escapes repository")
    authority_bytes = resolved_authority_path.read_bytes()
    require(len(authority_bytes) == expected["size_bytes"],
            f"{role} authority artifact size does not match accepted exact bytes")
    require("sha256:" + hashlib.sha256(authority_bytes).hexdigest() == expected["sha256"],
            f"{role} authority artifact sha256 does not match accepted exact bytes")
    authority_json = json.loads(authority_bytes.decode("utf-8"))
    require(authority_json.get("schema_id") == expected["schema_id"] and
            authority_json.get("schema_version") == 1 and
            authority_json.get("authority_id") == expected["id"] and
            authority_json.get("closed") is True and
            authority_json.get("status") == "diagnostic_not_physical_acceptance" and
            authority_json.get("geometry_role") == "plumbing_encoder_validation_only" and
            authority_json.get("camera_serial") == "2010093" and
            authority_json.get("coordinate_space") == "camera_native_0_indexed" and
            authority_json.get("camera_perspective") is True and
            authority_json.get("native_raster") == {"width": 4512, "height": 4512},
            f"{role} authority artifact is not closed camera-native diagnostic metadata")

expected_rois = [
    ("quadrant_top_left", "diagnostic_top_left", 0, 0),
    ("quadrant_top_right", "diagnostic_top_right", 2256, 0),
    ("quadrant_bottom_left", "diagnostic_bottom_left", 0, 2256),
    ("quadrant_bottom_right", "diagnostic_bottom_right", 2256, 2256),
]
rois = camera.get("rois", [])
require(len(rois) == 4, "spatial ROI config must contain exactly four ROIs")
for roi, (roi_id, region_id, x, y) in zip(rois, expected_rois):
    require(roi == {
                "roi_id": roi_id,
                "region_id": region_id,
                "required": True,
                "content_rect": {"x": x, "y": y, "width": 2256, "height": 2256},
                "logical_stream_id": f"2010093_spatial_roi_{roi_id}",
                "artifact_stem": f"Cam2010093_spatial_roi_{roi_id}",
            }, f"{roi_id} is not the canonical required 2010093 quadrant product")

runtime = fixed.get("spatial_roi_recorder_runtime", {})
require(runtime == {
            "schema_id": "orange.spatial_roi_recording.recorder_runtime",
            "schema_version": 1,
            "mode": "explicit_per_stream",
            "recorder_gpu_by_logical_stream_id": {
                "2010093_spatial_roi_quadrant_top_left": 1,
                "2010093_spatial_roi_quadrant_top_right": 2,
                "2010093_spatial_roi_quadrant_bottom_left": 1,
                "2010093_spatial_roi_quadrant_bottom_right": 2,
            },
        }, "spatial ROI recorder placement drifted")

require(spec.get("matrix") == {
            "codec": ["hevc"], "preset": ["p1"], "tuning": ["ll"],
            "rate_control_mode": ["vbr"], "quality_value": [20],
            "gop_length": [25], "aq": ["off"], "temporal_aq": ["off"],
            "lookahead": ["off"],
        }, "diagnostic experiment matrix drifted")

print("[spatial-roi-diagnostic] spec=pass")
print("[spatial-roi-diagnostic] camera=2010093 runtime_camera_id=0 raster=4512x4512 fps=100 source_gpu=3")
print("[spatial-roi-diagnostic] full_frame_split_gop=[3,4] roi_products=4xsingle_shard roi_gpus=[1,2,1,2]")
print("[spatial-roi-diagnostic] geometry=quadrants(top-left,top-right,bottom-left,bottom-right)")
print("[spatial-roi-diagnostic] geometry_status=plumbing/encoder_validation_only")
print("[spatial-roi-diagnostic] full_frame_recording=enabled yolo=off pose=off display=off")
print("[spatial-roi-diagnostic] authority=closed/versioned/camera-native diagnostic_not_physical_acceptance")
PY

if [[ "$EXECUTE" -eq 0 ]]; then
  echo "[spatial-roi-diagnostic] dry-run: validation/print only; no hardware or media execution"
  (
    cd "$REPO_ROOT"
    "$ORANGE_CLIENT" --mode local --experiment-spec "$SPEC" --validate-experiment-spec
  )
  exit 0
fi

echo "[spatial-roi-diagnostic] EXECUTE requested: hardware and media will be used"
echo "[spatial-roi-diagnostic] repo_root=$REPO_ROOT"
echo "[spatial-roi-diagnostic] spec=$SPEC"
echo "[spatial-roi-diagnostic] orange_client=$ORANGE_CLIENT"
echo "[spatial-roi-diagnostic] output_root=/home/jeremy/orange_data/exp/unsorted"
(
  cd "$REPO_ROOT"
  "$ORANGE_CLIENT" --mode local --experiment-spec "$SPEC"
)
